In [88]:
#pipeline ETL automatizado

import pandas as pd
import numpy as np

df=pd.read_csv(r'C:\Users\av-alumno\Documents\GitHub\Evalucion_Parcial_3\data\originales\FastFoodNutritionMenuV3.csv')

df.head()

,Company,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,McDonald’s,Hamburger,250,80,9,3.5,0.5,25,520,31,2,6,12,247.5
1,McDonald’s,Cheeseburger,300,110,12,6,0.5,40,750,33,2,6,15,297
2,McDonald’s,Double Cheeseburger,440,210,23,11,1.5,80,1150,34,2,7,25,433
3,McDonald’s,McDouble,390,170,19,8,1,65,920,33,2,7,22,383
4,McDonald’s,Quarter Pounder® with Cheese,510,230,26,12,1.5,90,1190,40,3,9,29,502

In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv('FastFoodNutritionMenuV3.csv')
df.head()

,Company,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,McDonald’s,Hamburger,250,80,9,3.5,0.5,25,520,31,2,6,12,247.5
1,McDonald’s,Cheeseburger,300,110,12,6,0.5,40,750,33,2,6,15,297
2,McDonald’s,Double Cheeseburger,440,210,23,11,1.5,80,1150,34,2,7,25,433
3,McDonald’s,McDouble,390,170,19,8,1,65,920,33,2,7,22,383
4,McDonald’s,Quarter Pounder® with Cheese,510,230,26,12,1.5,90,1190,40,3,9,29,502

# Extraer CSV

In [4]:
import pandas as pd
import logging

def extract_data(filepath):
    try:
        df = pd.read_csv(filepath)
        logging.info("Datos cargados correctamente")
        return df

    except FileNotFoundError:
        logging.error("Archivo no encontrado")
        raise

    except Exception as e:
        logging.error(f"Error inesperado: {e}")
        raise

# Limpieza

In [5]:
#revision de estructura
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1147 entries, 0 to 1146
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company               1147 non-null   object
 1   Item                  1147 non-null   object
 2   Calories              1147 non-null   object
 3   Calories from
Fat     642 non-null    object
 4   Total Fat
(g)         1091 non-null   object
 5   Saturated Fat
(g)     1091 non-null   object
 6   Trans Fat
(g)         1091 non-null   object
 7   Cholesterol
(mg)      1147 non-null   object
 8   Sodium
(mg)          1147 non-null   object
 9   Carbs
(g)             1091 non-null   object
 10  Fiber
(g)             1091 non-null   object
 11  Sugars
(g)            1147 non-null   object
 12  Protein
(g)           1091 non-null   object
 13  Weight Watchers
Pnts  887 non-null    object
dtypes: object(14)
memory usage: 125.6+ KB

## Renombrar columnas

In [6]:
#Renombramos columnas
#Calories from\nFat
#Total Fat\n(g)
#Saturated Fat\n(g)

df.columns = (
    df.columns
    .str.replace("\n", "_")
    .str.replace(" ", "_")
    .str.replace("(", "")
    .str.replace(")", "")
)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1140 entries, 0 to 1146
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company               1140 non-null   object
 1   Item                  1140 non-null   object
 2   Calories              1140 non-null   object
 3   Calories_from_Fat     1140 non-null   object
 4   Total_Fat_g           1140 non-null   object
 5   Saturated_Fat_g       1140 non-null   object
 6   Trans_Fat_g           1140 non-null   object
 7   Cholesterol_mg        1140 non-null   object
 8   Sodium__mg            1140 non-null   object
 9   Carbs_g               1140 non-null   object
 10  Fiber_g               1140 non-null   object
 11  Sugars_g              1140 non-null   object
 12  Protein_g             1140 non-null   object
 13  Weight_Watchers_Pnts  1140 non-null   object
dtypes: object(14)
memory usage: 133.6+ KB

## Limpiar duplicados

In [7]:
df.drop_duplicates(inplace=True)

## Manejo de nulos

In [8]:
df.isnull().sum()

Company                   0
Item                      0
Calories                  0
Calories_from_Fat       505
Total_Fat_g              56
Saturated_Fat_g          56
Trans_Fat_g              56
Cholesterol_mg            0
Sodium__mg                0
Carbs_g                  56
Fiber_g                  56
Sugars_g                  0
Protein_g                56
Weight_Watchers_Pnts    260
dtype: int64

In [9]:
df.fillna(0, inplace=True)

In [10]:
df.isnull().sum()

Company                 0
Item                    0
Calories                0
Calories_from_Fat       0
Total_Fat_g             0
Saturated_Fat_g         0
Trans_Fat_g             0
Cholesterol_mg          0
Sodium__mg              0
Carbs_g                 0
Fiber_g                 0
Sugars_g                0
Protein_g               0
Weight_Watchers_Pnts    0
dtype: int64

# Cambiar tipo de las variables

In [22]:
df['Calories'] = df['Calories'].astype(bool)
df['Sodium__mg'] = df['Sodium__mg'].astype(bool)
df['Total_Fat_g'] = df['Total_Fat_g'].astype(bool)

## Calorias negativas

In [ ]:
df = df[df["Calories"] >= 0]

## Sodio negativo

In [19]:
df = df[df["Sodium__mg"] >= 0]

## Grasas negativas

In [20]:
df = df[df["Total_Fat_g"] >= 0]

## Crear variables nuevas

In [21]:
def calorie_category(x):

    if x < 300:
        return "Baja"

    elif x < 600:
        return "Media"

    else:
        return "Alta"

df["Calorie_Category"] = df["Calories"].apply(calorie_category)